server:
  port: 8080

spring:
  application:
    name: zuul-gateway

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

zuul:
  routes:
    student-service:
      path: /student/**
      url: http://localhost:8082/student
    instructor-service:
      path: /instructor/**
      url: http://localhost:8081/instructor